### ISSUE TITLE
Tskit for teaching?

### ISSUE THREAD

**Issue by hyanwong** [petrelharp/progen-2023#1]
Do we want any emphasis on the ability to teach students using tskit at all? E.g. any of the jupyterlite stuff?

**Comment by jeromekelleher** [comment]
Do we have any deployments to point at?

**Comment by jeromekelleher** [comment]
Ooh, it'd be cool if there was a link to a deployment with a QR code on the poster.

**Comment by jeromekelleher** [comment]
msprime running on your phone :muscle:

**Comment by jeromekelleher** [comment]
Ah, of course @molpopgen has already done something similar: 

https://observablehq.com/collection/@molpopgen/coalescent-theory

**Comment by molpopgen** [comment]
I got rather deep into using msprime to illustrate concepts from coalescent theory over the last two weeks.  The feedback has been positive.  It is a bit painful for the instructor!  And it can all run on a phone.

**Comment by molpopgen** [comment]
I've also made several interactive things for classes using msprime/tskit + Jupyter: https://www.molpopgen.org/visual-popgen/intro.html.  These have the disadvantage of needing a service to spin up a Docker instance to run an interactive session.    I haven't found a solution to a runner that I don't have to pay for, don't have to manage, etc..  I think that students lose interest when these are spinning up, especially on mobile where it can take ages.

**Comment by hyanwong** [comment]
It's mentioned via #14 (Jupyterlite as the display item). So I guess we can close this, unless anyone actually wants to make a QR code that points to a running instance. Not really enough time for that I guess.

**Comment by molpopgen** [comment]
![6701751fa47b48275ec8c9c9743abcb6](https://user-images.githubusercontent.com/6416159/222555946-f7aa7cd9-a544-4cc1-ba5f-2e38130f983f.png)

Here's one for my notebooks using msprime/tskit.
