### ISSUE TITLE
New features: numba example?

### ISSUE THREAD

**Issue by gtsambos** [petrelharp/progen-2023#4]
I spent the afternoon looking into numba -- wow!!

Can anyone think of a good algorithm that we could demonstrate it with? Ideally one with a bit of iteration over tree/ts attributes that we can access as numpy arrays? I've looked through @jeromekelleher's examples [here](https://github.com/tskit-dev/tutorials/issues/63), but many of these are copies of tskit methods that are already coded in C.

I've tried to numba-fy the example in the tutorials [here](https://tskit.dev/tskit/docs/stable/topological-analysis.html?highlight=numba#ascending-traversal), but it seems to be slightly slower than the inbuilt tskit method using `tree.parent()`, so this might not be the best demo case...

**Comment by gtsambos** [comment]
> I've tried to numba-fy the example in the tutorials [here](https://tskit.dev/tskit/docs/stable/topological-analysis.html?highlight=numba#ascending-traversal)

(putting my numba code here in case someone sees a smarter way to do this)
```
def find_paths_numba(tree, samples):
    pa = tree.parent_array
    for u in samples:
        path = []
        v = u
        while v != -1:
            path.append(v)
            v = get_parent(pa, v)

@numba.jit
def get_parent(parent_arr, n):
    return parent_arr[n]

find_paths_numba(t0, ts0.samples())
```

**Comment by gtsambos** [comment]
d'oh. just as I posted, I realised I could do this
```
def find_paths_numba2(tree, samples):
    pa = tree.parent_array
    for u in samples:
        get_parents(pa, u)

@numba.jit
def get_parents(parent_arr, child):
    path = []
    v = child
    while v != -1:
        path.append(v)
        v = parent_arr[v]
    return path

find_paths_numba2(t0, ts0.samples())
```
and it is now magnitudes faster than the example!

**Comment by gtsambos** [comment]
(for reference, the improved numba implementation works on a tree with 200000 samples in 0.3 s. Vanilla tskit implementation is 1.7s, and my old stupid way ran in 2.4s).

**Comment by jeromekelleher** [comment]
There's some more algorithms in the experimental [phylokit](https://github.com/jeromekelleher/phylokit/) package.  The [balance metrics](https://github.com/jeromekelleher/phylokit/blob/main/phylokit/balance.py) are probably the best example of usage. These are all almost as fast as the tskit C implementations!

Something like total branch length could be a good example:
```python

@numba.njit
def _total_branch_length(preorder, parent, node_time):
     tbl = 0
     for u in preorder:
          if parent[u] != -1:
               tbl += node_time[parent[u]] - node_time[u]
     return tbl

def get_total_branch_length(tree):
     return _total_branch_length(tree.preorder(), tree.parent_array, tree.tree_sequence.nodes_time)
```

(Untested)

**Comment by gtsambos** [comment]
thanks @jeromekelleher, those look cool!

It'd be cool to see how the total_branch_length function compares to the branch stat implementation of the "number of segregating sites" statistic (I think these are equivalent up to a constant under some assumptions.)

**Comment by jeromekelleher** [comment]
Can compare directly with tskit [method](https://tskit.dev/tskit/docs/stable/python-api.html#tskit.Tree.total_branch_length), which is implemented in C.

Also fun to compare timing with ``sum(tree.branch_length(u) for u in tree.nodes())``

**Comment by gtsambos** [comment]
thanks @jeromekelleher, I ended up using this as the example. It is pretty much as fast as `total_branch_length`. On a tree with a few tens of 1000s of nodes, it's ~ 100 times faster than the method using the `nodes()` iterator
